### ISSUE TITLE
native zp_is_infection_round(), zp_is_multi_round()

### ISSUE THREAD

**Issue by Balage74** [PerfectScrash/Zombie-Plague-Special#1]
Hi! 
Please implement this 2 native to next release:
zp_is_infection_round()
zp_is_multi_round()
 
Its mod is beautyful and i write some plugin under this version and  discover some deficiency. This is just what I remember, but if I remember the rest, write it.
Thx.

**Comment by PerfectScrash** [comment]
The native are unecessary when you can create in a stock.
Use ZPSp 4.4 includes (Now divided in 3 parts)
