### ISSUE TITLE
a sort of solution for register_extra_item & extra item menu buy problem

### ISSUE THREAD

**Issue by Balage74** [PerfectScrash/Zombie-Plague-Special#2]
I've been thinking for a long time about how to solve the extra item shopping problem for other bosses. I made an entity from leap ability and can buy on extra item menu. Little hard  what I could assign buy/use but find solution (little "backdoor" for scripters:D) Just look in my code zp_user_infected_post (or humanize) 
I haven't tested it completely yet, but it seems to work. (this code wrong but design usable, i will send later the real good solution.)
[zp_extra_leap_native.zip](https://github.com/PerfectScrash/Zombie-Plague-Special/files/3222369/zp_extra_leap_native.zip)

**Comment by PerfectScrash** [comment]
Sorry for the delay, i was busy with studies
for backward versions of 4.4 add this line bellow of #include <zombie_plague_special>
native zp_get_special_class_name(id, name[], len)

and Thanks for repport
