### ISSUE TITLE
Armaggedon Mode - Survivor respawning as human

### ISSUE THREAD

**Issue by iogh07** [PerfectScrash/Zombie-Plague-Special#3]
Hello.
If Armaggedon Mode is starting, the players are transformed into Nemeses and Survivors, but if the player dies and respawns, is becoming human, not survivor.
Can you check the problem please?
Couldn't find a solution for it.

**Comment by PerfectScrash** [comment]
Try Test an small correction updated in 08/12/2020 (Today) Here: https://github.com/PerfectScrash/Zombie-Plague-Special/tree/master/Zombie%20Plague%20Special%204.4%20(Final%20Beta)

**Comment by iogh07** [comment]
Problem solved. Thank you!
